environment:
  matrix:
    - nodejs_version: "6.9.0"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"

matrix:
  fast_finish: true # build fail immediately once one of the job fails

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - appveyor DownloadFile "https://downloads.sourceforge.net/project/graphicsmagick/graphicsmagick-binaries/1.3.25/GraphicsMagick-1.3.25-Q16-win64-dll.exe?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fgraphicsmagick%2Ffiles%2Fgraphicsmagick-binaries%2F1.3.25%2F&ts=1492874765&use_mirror=iweb"
  - GraphicsMagick-1.3.25-Q16-win64-dll.exe /SP /VERYSILENT /NORESTART /NOICONS /DIR=%CD%\gm
  - set PATH=%CD%\gm;%PATH%
  - yarn install

test_script:
  - node --version
  - npm --version
  - gm version
  - yarn lint
  - yarn test
  - yarn test:react

build_script:
  - yarn run webpack
