environment:
  matrix:
    - nodejs_version: "6.9.0"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"

matrix:
  fast_finish: true # build fail immediately once one of the job fails

platform:
  - x86
  - x64

install:
  # Install GraphicsMagick
  - appveyor DownloadFile "http://ftp.icm.edu.pl/pub/unix/graphics/GraphicsMagick/windows/GraphicsMagick-1.3.26-Q16-win64-dll.exe"
  - GraphicsMagick-1.3.26-Q16-win64-dll.exe /SP /VERYSILENT /NORESTART /NOICONS /DIR=%CD%\gm
  - set PATH=%CD%\gm;%PATH%
  # Get the wanted version of Node
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install

test_script:
  - node --version
  - npm --version
  - gm version
  - yarn lint
  - yarn test
  - yarn test:react

build_script:
  - yarn run webpack
