engines:
  duplication:
       enabled: true
       config:
         languages:
           javascript:
             mass_threshold: 70
       exclude_paths:
           - "server/plugins/album/public/lib/color-thief.js"
           - "server/plugins/album/test/cases.js"
           - "server/plugins/editAlbum/public/lib/json_to_xml.js"
  eslint:
    enabled: false
    channel: "eslint-4"
    config:
        extensions:
        - .js
        - .jsx

ratings:
   paths:
   - "**.js"
   - "**.jsx"
