language: node_js

addons:
  apt:
    packages:
    - graphicsmagick

node_js:
  - "6.9.0"
  - "6"
  - "7"

before_install:
  - npm install -g yarn --cache-min 999999999
install:
  - yarn install

scripts:
  - yarn ci
after_success:
  - yarn ci-cover:coveralls
